-- ============================================================================
-- Student Management System - Complete database schema + seed data
-- ============================================================================
-- A single, ready-to-import script (phpMyAdmin / mysql CLI).
--
--     mysql -u root -p < database.sql
--
-- It DROPS and recreates the whole database, so running it resets everything.
-- The admin password is "12345" and is stored ONLY as a BCrypt hash (never
-- plaintext). The hash below was produced by the application's own
-- PasswordHasher (BCrypt.Net.BCrypt.HashPassword("12345")).
-- ============================================================================

DROP DATABASE IF EXISTS student_management;
CREATE DATABASE student_management
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;
USE student_management;

-- ----------------------------------------------------------------------------
-- users
-- ----------------------------------------------------------------------------
CREATE TABLE users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'user',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_users_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------------
-- courses
-- ----------------------------------------------------------------------------
CREATE TABLE courses (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    code VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    units TINYINT UNSIGNED NOT NULL DEFAULT 3,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_courses_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------------
-- students
-- ----------------------------------------------------------------------------
CREATE TABLE students (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    student_number VARCHAR(20) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NULL,
    phone VARCHAR(20) NULL,
    course_id INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_students_student_number (student_number),
    KEY idx_students_course_id (course_id),
    CONSTRAINT fk_students_course FOREIGN KEY (course_id)
        REFERENCES courses (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------------
-- enrollments
-- ----------------------------------------------------------------------------
CREATE TABLE enrollments (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    student_id INT UNSIGNED NOT NULL,
    course_id INT UNSIGNED NOT NULL,
    grade DECIMAL(5,2) NULL,
    enrolled_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_enrollments_student_course (student_id, course_id),
    KEY idx_enrollments_course_id (course_id),
    CONSTRAINT fk_enrollments_student FOREIGN KEY (student_id)
        REFERENCES students (id) ON DELETE CASCADE,
    CONSTRAINT fk_enrollments_course FOREIGN KEY (course_id)
        REFERENCES courses (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================================
-- Seed data
-- ============================================================================

-- Admin account. Password: 12345 (BCrypt hash, generated by the app).
INSERT INTO users (username, password_hash, role) VALUES
    ('admin', '$2a$11$tnk9I.0L7SKlZVaBZLTTZ.Vu9SgO5tb6Z2mF0d5P57lKHK5Xkvm96', 'admin');

-- Sample courses.
INSERT INTO courses (code, name, units) VALUES
    ('CS101',  'Introduction to Computing', 3),
    ('CS201',  'Data Structures',           3),
    ('MATH101','Calculus',                  4),
    ('ENG101', 'English',                   3),
    ('SCI101', 'Physics',                   3);

-- Sample students.
INSERT INTO students (student_number, first_name, last_name, email, phone, course_id) VALUES
    ('S001', 'John',   'Doe',    'john.doe@example.com',    '09171234567', 1),
    ('S002', 'Jane',   'Smith',  'jane.smith@example.com',  '09179876543', 2),
    ('S003', 'Maria',  'Garcia', 'maria.garcia@example.com','09178001122', 3),
    ('S004', 'Peter',  'Pan',    'peter.pan@example.com',   '09175554433', 4),
    ('S005', 'Anna',   'Brown',  'anna.brown@example.com',  '09176667788', 5),
    ('S006', 'Luis',   'Reyes',  'luis.reyes@example.com',  '09178889900', NULL);

-- Sample enrollments (with and without grades).
INSERT INTO enrollments (student_id, course_id, grade) VALUES
    (1, 1, NULL),
    (1, 3, 92.50),
    (2, 2, 88.00),
    (2, 1, NULL),
    (3, 3, 95.00),
    (5, 5, NULL);
