-- Reference seed script for the Student Management System.
-- Run this once against MySQL (e.g. via phpMyAdmin or the mysql CLI) BEFORE first login.
--
-- IMPORTANT: This script must NEVER contain a plaintext password.
-- The admin password_hash below is a placeholder; the real hash must be
-- generated by the application (see Data/PasswordHasher.cs) so that no
-- plaintext password ever lives in source control.
--
-- Alternative: call UserRepository.EnsureSchema() from the app and insert the
-- admin user through the app itself, then delete this placeholder row.

CREATE DATABASE IF NOT EXISTS student_management
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE student_management;

CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'user',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_users_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Placeholder admin row. REPLACE password_hash with a real BCrypt hash
-- produced by the application before using this in production.
INSERT INTO users (username, password_hash, role)
SELECT 'admin', 'REPLACE_WITH_A_BCRYPT_HASH_FROM_THE_APP', 'admin'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'admin');